from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
from enum import Enum

class Role(str, Enum):
    student = "student"
    developer = "developer"
    educator = "educator"
    admin = "admin"

class Background(str, Enum):
    beginner = "beginner"
    intermediate = "intermediate"
    advanced = "advanced"

class HardwareLevel(str, Enum):
    simulator_only = "simulator-only"
    basic_hardware = "basic-hardware"
    advanced_hardware = "advanced-hardware"

class QuestionType(str, Enum):
    general = "general"
    selected_text = "selected_text"

class PreferredHardwareExamples(str, Enum):
    simulator = "simulator"
    real_hardware = "real_hardware"
    both = "both"

class ExperienceLevel(str, Enum):
    beginner = "beginner"
    intermediate = "intermediate"
    advanced = "advanced"

class LearningPace(str, Enum):
    slow = "slow"
    normal = "normal"
    fast = "fast"

class BookModule(BaseModel):
    """
    Represents one of the four main topics (ROS 2, Gazebo, Isaac Sim, VLA) with associated content, exercises, and examples
    """
    id: str
    title: str
    description: str
    order: int
    learning_objectives: List[str]
    summary: str
    checklist: List[str]
    word_count: int

class Chapter(BaseModel):
    """
    A sub-section of a module containing learning objectives, content, summary, and checklist
    """
    id: str
    module_id: str
    title: str
    content: str
    order: int
    learning_objectives: List[str]
    summary: str
    checklist: List[str]
    word_count: int

class User(BaseModel):
    """
    A registered user who can access personalized content and features
    """
    id: str
    email: str
    username: Optional[str] = None
    password_hash: str  # This would typically be a hashed password
    role: Role
    background: Background
    hardware_level: HardwareLevel
    preferred_language: str = "en"  # Also supports "ur" for Urdu
    created_at: datetime
    updated_at: datetime

class Question(BaseModel):
    """
    A query submitted to the RAG chatbot about book content
    """
    id: str
    user_id: Optional[str] = None  # Optional for anonymous questions
    question_text: str
    question_type: QuestionType
    selected_text: Optional[str] = None  # Required if question type is "selected_text"
    book_section_id: Optional[str] = None  # To track which section user was reading
    created_at: datetime

class Answer(BaseModel):
    """
    A response generated by the RAG chatbot based on book content
    """
    id: str
    question_id: str
    answer_text: str
    source_chunks: List[str]  # IDs of content chunks used
    confidence_score: float  # 0.0-1.0
    generated_at: datetime

class CodeExample(BaseModel):
    """
    A reproducible code block with specific version requirements
    """
    id: str
    chapter_id: str
    title: str
    code: str
    language: str  # e.g., "python", "bash", "yaml", "xml"
    version_requirements: str  # e.g., "ROS 2 Humble", "Python 3.8+"
    execution_notes: str
    expected_output: str

class Exercise(BaseModel):
    """
    Hands-on exercise associated with a chapter
    """
    id: str
    chapter_id: str
    title: str
    description: str
    difficulty: Background  # Using the Background enum for difficulty
    instructions: str
    solution: str
    hints: List[str]

class ChatLog(BaseModel):
    """
    Log of user interactions with the RAG chatbot
    """
    id: str
    user_id: Optional[str] = None
    question_id: str
    answer_id: str
    timestamp: datetime
    session_id: str  # To group related questions

class PersonalizationSettings(BaseModel):
    """
    User-specific settings that affect content delivery
    """
    id: str
    user_id: str
    preferred_hardware_examples: PreferredHardwareExamples
    experience_level: ExperienceLevel
    favorite_topics: List[str]
    learning_pace: LearningPace
    notification_preferences: dict  # email, push, etc.

class ImageMedia(BaseModel):
    """
    Visual content with proper attribution information
    """
    id: str
    chapter_id: str
    filename: str
    title: str
    alt_text: str
    attribution: str  # Source information
    license: str  # e.g., "CC BY", "AI-generated", etc.
    usage_notes: str  # Where and how the image should be used